VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "SheetObjects_InitDelegate"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit
Public Property Get TypeName() As String

End Property

Public Sub constructVariable(nameRange As Range, typeRange As Range, _
                                baseAddressRange As Range, Contents As Range, varRange As Range)
    
End Sub

